### ISSUE TITLE
move all gitea repo's into github

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_archive#3]
only the ones not being archived

- mark & review in spreadsheet what locations will be, which accounts, see if we have enough..., see with KDS
-  make sure despiegk can access all, replace links on gdoc and remove from gitea

**Comment by sasha-astiadi** [comment]
its not clear to me, whcih gitea repos? 
if i log into docs.grid.tf - i only have access to 1 org with 1 repo.

![Image](https://user-images.githubusercontent.com/43240801/178517189-35b95275-d130-4152-8bfc-20253859ed2f.png)


please give me access to whichever that you want me to move to github.

- which org to gite (link pls)
- which repos? all? 
- how to do (because gitea to github -- might be only doable by zipping, we might lose commit histories,... also maybe can research how to do it properly.
@remrekoc

**Comment by sasha-astiadi** [comment]
nothing in ggitea, only itnv dev env.. closing issue
